apiVersion: v1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinspv
  labels:
    name: jenkinspv
spec:
  nfs:
    path: /data/devops/jenkins
    server: 192.168.1.10
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: jenkinspvc
 namespace: devops
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 3Gi
