apiVersion: v1
kind: PersistentVolume
metadata:
 name: jenkinspv
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Delete
 nfs:
   server: 192.168.1.10
   path: /data/devops/jenkins
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: jenkinspvc
 namespace: devops
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 3Gi
