apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "maven-repo"
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi